{
    'name': 'Hospital Management System',
    'author': 'Odoo Mates',
    'website': 'www.odoomates.tech',
    'summary': 'odoo 16 Development',
    'depends': ['mail', 'sale', 'report_xlsx', 'jalak_hms_base', 'jalak_hms'],
# 'assets': {
#     'web.assets_backend': [
#         'dev/om_abi/static/src/css/appointment_style.css',
#     ]},
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'wizard/create_appointment_view.xml',
        'wizard/hms_surat_sakit_view.xml',
        'wizard/hms_surat_sehat_view.xml',
        'views/menu.xml',
        'views/patient.xml',
        'views/kid.xml',
        'views/patient_gender.xml',
        'views/doctor.xml',
        'views/appointment.xml',
        'views/sale.xml',
        'views/hms_patient.xml',
        'report/report.xml',
        'report/patient_card.xml',
        'report/patient_card_2.xml',
        'report/appointment_details.xml',
        'report/surat_sakit.xml',
        'report/surat_sehat.xml',
        'views/hms_appointment.xml',
    ],
    'demo': [],
    'qweb': [],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,

}
